policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      spellcheck:
        locale: US
      conventional:
        types:
          - feat
          - fix
          - build
          - chore
          - ci
          - docs
          - pref
          - refactor
          - style
          - test
        scopes:
          - flake
          - github
          - module
        descriptionLength: 72
