jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            max-jobs = auto
      - uses: cachix/cachix-action@v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: cuda-maintainers
          name: terlar
          useDaemon: true
      - run: nix eval .#tests.first-ci-kit
      - run: nix flake check
name: CI
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
