jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            max-jobs = auto
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
      - uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: cuda-maintainers
          name: terlar
          useDaemon: true
      - run: nix eval .#tests.first-ci-kit
      - run: nix flake check
name: CI
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
